stages:
  - build
  - deploy

build:
  stage: build
  image: node:latest
  tags:
    - docker_builder
  script:
    - npm i cnpm --registry https://registry.npm.taobao.org
    - cnpm i || npm i
    - npm run build
  artifacts:
    paths:
      - dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

deploy:
  stage: deploy
  image: node:latest
  tags:
    - docker_builder
  script:
    - npx @getmeli/cli upload --url https://meli.staging.feel.ac.cn --site $MELI_PREVIEW_SITE --token $MELI_PREVIEW_TOKEN --branch preview -r $CI_COMMIT_SHORT_SHA ./dist
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  environment:
    name: devlopment
    url: https://welishi.cn/
